### ISSUE TITLE
Errno::ETIMEDOUT when registering

### ISSUE THREAD

**Issue by jasonvillalon** [sameersbn/docker-gitlab-ci-runner#15]
Hi, 

i already setup my gitlab and gitlab ci but when installing gitlab-ci-runner i receive this error. any idea?

Registering runner as <MYTOKEN> with registration token: 5e1380dfcc2e, url: http://192.168.2.19:10080/.
/usr/lib/ruby/2.1.0/net/http.rb:879:in `initialize': Connection timed out - connect(2) for "192.168.2.19" port 10080 (Errno::ETIMEDOUT)
	from /usr/lib/ruby/2.1.0/net/http.rb:879:in `open'
	from /usr/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
	from /usr/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
	from /usr/lib/ruby/2.1.0/net/http.rb:878:in `connect'
	from /usr/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
	from /usr/lib/ruby/2.1.0/net/http.rb:852:in `start'
	from /usr/lib/ruby/2.1.0/net/http.rb:1369:in `request'
	from /home/gitlab_ci_runner/gitlab-ci-runner/vendor/bundle/ruby/2.1.0/gems/httparty-0.11.0/lib/httparty/request.rb:92:in `perform'
	from /home/gitlab_ci_runner/gitlab-ci-runner/vendor/bundle/ruby/2.1.0/gems/httparty-0.11.0/lib/httparty.rb:461:in `perform_request'
	from /home/gitlab_ci_runner/gitlab-ci-runner/vendor/bundle/ruby/2.1.0/gems/httparty-0.11.0/lib/httparty.rb:414:in `post'
	from /home/gitlab_ci_runner/gitlab-ci-runner/lib/network.rb:88:in `register_runner'
	from /home/gitlab_ci_runner/gitlab-ci-runner/lib/setup.rb:38:in `register_runner'
	from /home/gitlab_ci_runner/gitlab-ci-runner/lib/setup.rb:9:in `initialize'
	from ./bin/setup:5:in `new'
	from ./bin/setup:5:in `<main>'

**Comment by Excelecio** [comment]
try this url : ```http://172.17.42.1:10080```
